adding mongo configuration
jlopez513573/MPW-Store pull request #10
Opened 2023-04-13 19:35 UTC by julianarce1995

2023-04-13 21:07 UTC, julianarce1995 commented on src/pages/utils/dbconnection.ts
> +import { connect, connection } from "mongoose";
ah ok entonces deberia ser con mongodb y no con mongoose.

2023-04-13 21:12 UTC, jlopez513573 commented on src/pages/utils/dbconnection.ts
> +import { connect, connection } from "mongoose";
@julianarce1995 bueno, lo que pasa es que Mongoose es una libreria para facilitar la coneccion y la forma de consultar la base de datos... pero tambien sirve...

Hazlo como dice en esta pagina y lo pruebas...

2023-04-13 21:16 UTC, julianarce1995 commented on src/pages/utils/dbconnection.ts
> +import { connect, connection } from "mongoose";
cual es la pagina?

2023-04-13 21:35 UTC, jlopez513573 commented on src/pages/utils/dbconnection.ts
> +import { connect, connection } from "mongoose";
https://itnext.io/using-mongoose-with-next-js-11-b2a08ff2dd3c

2023-04-19 22:12 UTC, jlopez513573 requested changes

2023-04-19 22:12 UTC, jlopez513573 commented on src/utils/dbconnection.ts
> +import { connect, connection } from "mongoose";
creo que este archivo ya no es necesario

2023-04-19 22:12 UTC, jlopez513573 commented on src/pages/api/index.ts
> +export default async function handler(req:any, res:any) {
tratemos de nunca usar any. busca en la documentacion cual deberia ser el Type correcto tanto para req como para res

2023-04-19 22:12 UTC, jlopez513573 commented on src/pages/_app.tsx
> +//import '@/styles/globals.css'
no creo que necesitemos comentar esto no?

2023-04-19 22:12 UTC, jlopez513573 commented on src/models/schemas/UserSchema.ts
> +export default userSchema
siempre dejemos una linea nueva al final de cada archivo

2023-04-19 22:12 UTC, jlopez513573 commented on src/models/Users.ts
> +export default User;
nueva linea tambien

2023-04-19 22:12 UTC, jlopez513573 commented on lib/mongodb.ts
> +/*import { MongoClient, MongoClientOptions } from 'mongodb'
eliminemos este codigo y dejemos una nueva linea al final del archivo

2023-04-21 15:33 UTC, merged